# Generated by Django 2.2 on 2023-07-21 00:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('Mi', 'Miercoles'), ('J', 'Jueves'), ('V', 'viernes')], default='L', max_length=9, verbose_name='Día de la semana')),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('razon_social', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('web', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('num_doc', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='N° de documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido/s')),
                ('num_cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de CUIT/CUIL')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de teléfono ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=120)),
                ('hc', models.IntegerField(blank=True, null=True, verbose_name='N° historia clínica')),
                ('titular_familiar', models.CharField(blank=True, default='No requiere', max_length=250, null=True, verbose_name='Familiar titular')),
                ('obra_social', models.ForeignKey(default='Ninguna', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_obraSocial', to='odontologia.ObraSocial', verbose_name='Obra Social')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('pieza_dental', models.ManyToManyField(related_name='pieza_dental_prestacion', to='odontologia.PiezaDental')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('num_doc', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='N° de documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido/s')),
                ('num_cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de CUIT/CUIL')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de teléfono ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=120)),
                ('matricula', models.IntegerField(unique=True)),
                ('especialidad', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Reservado', max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_turno', to='odontologia.Profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_turno', to='odontologia.Paciente')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('observacion', models.TextField()),
                ('prestacion', models.ManyToManyField(related_name='prestacion_tratamiento', to='odontologia.Prestacion')),
                ('profesional', models.ManyToManyField(related_name='medico_tratamiento', to='odontologia.Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('factor', models.CharField(choices=[('a_mas', 'A+'), ('a_menos', 'A-'), ('b_mas', 'B+'), ('b_menos', 'B-'), ('ab_mas', 'AB+'), ('ab_menos', 'AB-'), ('o_mas', 'O+'), ('o_menos', 'O-')], max_length=15, verbose_name='Factor sanguineo')),
                ('antecedentes', models.TextField(verbose_name='Antecedentes médicos')),
                ('medicacion', models.TextField()),
                ('establecimiento', models.ManyToManyField(related_name='establecimiento_ficha_medica', to='odontologia.Establecimiento')),
                ('historia_clinica', models.ManyToManyField(related_name='historia_clinica_ficha', to='odontologia.Tratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_ficha_medica', to='odontologia.Paciente')),
                ('prestacion', models.ManyToManyField(related_name='prestacion_ficha_medica', to='odontologia.Prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario_turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_hora_calendario_turnos', to='odontologia.Calendario')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_calendario_turnos', to='odontologia.Profesional')),
            ],
        ),
    ]
