# Generated by Django 3.2.6 on 2021-09-08 01:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_doc', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='N° de documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido/s')),
                ('num_cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de CUIT/CUIL')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de naicmiento')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de teléfono ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=120)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='odontologia.localidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc', models.IntegerField(verbose_name='N° historia clínica')),
                ('titular_familiar', models.CharField(blank=True, max_length=250, null=True, verbose_name='Familiar titular')),
                ('numOS', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_obraSocial', to='odontologia.obrasocial')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_paciente', to='odontologia.persona')),
            ],
        ),
    ]
