# Generated by Django 2.2 on 2023-07-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
