# Generated by Django 3.2.6 on 2021-09-14 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('Mi', 'Miercoles'), ('J', 'Jueves'), ('V', 'viernes')], default='L', max_length=9, verbose_name='Día de la semana')),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('razon_social', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('web', models.CharField(blank=True, max_length=250, null=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidad_establecimiento', to='odontologia.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('pieza_dental', models.ManyToManyField(related_name='pieza_dental_prestacion', to='odontologia.PiezaDental')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('contraseña', models.CharField(max_length=150)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_usuario', to='odontologia.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_turno', to='odontologia.profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_turno', to='odontologia.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('observacion', models.TextField()),
                ('prestacion', models.ManyToManyField(related_name='prestacion_tratamiento', to='odontologia.Prestacion')),
                ('profesional', models.ManyToManyField(related_name='medico_tratamiento', to='odontologia.Profesional')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_profesional', to='odontologia.persona'),
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('factor', models.CharField(choices=[('a_mas', 'A+'), ('a_menos', 'A-'), ('b_mas', 'B+'), ('b_menos', 'B-'), ('ab_mas', 'AB+'), ('ab_menos', 'AB-'), ('o_mas', 'O+'), ('o_menos', 'O-')], max_length=15, verbose_name='Factor sanguineo')),
                ('antecedentes', models.TextField(verbose_name='Antecedentes médicos')),
                ('medicacion', models.TextField()),
                ('establecimiento', models.ManyToManyField(related_name='establecimiento_ficha_medica', to='odontologia.Establecimiento')),
                ('historia_clinica', models.ManyToManyField(related_name='historia_clinica_ficha', to='odontologia.Tratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_ficha_medica', to='odontologia.paciente')),
                ('prestacion', models.ManyToManyField(related_name='prestacion_ficha_medica', to='odontologia.Prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario_turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_hora_calendario_turnos', to='odontologia.calendario')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_calendario_turnos', to='odontologia.profesional')),
            ],
        ),
    ]
