# Generated by Django 3.2.6 on 2021-09-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0003_auto_20210925_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='numOS',
            new_name='obra_social',
        ),
    ]
