# Generated by Django 3.2.6 on 2021-09-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0004_rename_numos_paciente_obra_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='titular_familiar',
            field=models.CharField(blank=True, default='No requiere', max_length=250, null=True, verbose_name='Familiar titular'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='num_doc',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='N° de documento'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='Reservado', max_length=10),
        ),
    ]
