# Generated by Django 3.2.6 on 2021-09-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia', '0005_auto_20210927_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(default='Ninguna', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_obraSocial', to='odontologia.obrasocial', verbose_name='Obra Social'),
        ),
    ]
